/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 51 "main.c"
char __KOOC_3Foo_1a4char  =    (char )'c';
#line 56 "main.c"
int __KOOC_3Foo_3toz4void(void) 
{ 


  {
#line 56
  return (0);
}
}
#line 57 "main.c"
int _KOOC_3Foo_6foobar3int4char3int(char c , int a ) 
{ 


  {
#line 57
  return (0);
}
}
#line 61
extern int ( /* missing proto */  __KOOC_3Foo_6foobar3int4char3int)() ;
#line 61 "main.c"
int main(void) 
{ 


  {
#line 61
  __KOOC_3Foo_3toz4void();
#line 61
  printf((char const   * __restrict  )"%c\n", (int )__KOOC_3Foo_1a4char);
#line 61
  __KOOC_3Foo_6foobar3int4char3int('l', 3);
#line 61
  return (0);
}
}
