/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 695 "/usr/include/stdio.h"
extern int puts(char const   *__s ) ;
#line 3 "main.c"
int k  ;
#line 4 "main.c"
void foo(char *a , int *b ) 
{ 


  {
#line 25
  puts("Begin");
#line 6
  if (k) {
#line 8
    puts("");
#line 9
    if (k - 1) {
#line 11
      puts("");
#line 30
      puts("Before before end");
#line 31
      puts("Before end");
#line 12
      return;
    }
  } else
#line 15
  if (- k) {
#line 17
    puts("");
#line 30
    puts("Before before end");
#line 31
    puts("Before end");
#line 18
    return;
  }
#line 20
  puts("End");
#line 30
  puts("Before before end");
#line 31
  puts("Before end");
#line 21
  return;
}
}
#line 36 "main.c"
int main(void) 
{ 
  int n ;
  void (*f)(char *a , int *b ) ;

  {
#line 39
  f = & foo;
#line 40
  (*f)((char *)"lol", & n);
#line 41
  return (0);
}
}
