/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 63
@module Bar {
#line 65 "main.c"
int a   = 3;
#line 64
extern int foo(char c , int a ) ;
}
#line 67 "main.c"
int main(void) 
{ 


  {
#line 69
  return (0);
}
}
